Plugins/Nop.Plugin.Shipping.EasyPost/Models/Configuration/ConfigurationModel.cs
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using Microsoft.AspNetCore.Mvc.Rendering;
using Nop.Web.Framework.Models;
using Nop.Web.Framework.Mvc.ModelBinding;

namespace Nop.Plugin.Shipping.EasyPost.Models.Configuration
{
    /// <summary>
    /// Represents configuration model
    /// </summary>
    public record ConfigurationModel : BaseNopModel
    {
        #region Ctor

        public ConfigurationModel()
        {
            CarrierAccounts = new List<string>();
            AvailableCarrierAccounts = new List<SelectListItem>();
        }

        #endregion

        #region Properties

        [NopResourceDisplayName("Plugins.Shipping.EasyPost.Configuration.Fields.ApiKey")]
        [DataType(DataType.Password)]
        public string ApiKey { get; set; }

        [NopResourceDisplayName("Plugins.Shipping.EasyPost.Configuration.Fields.TestApiKey")]
        [DataType(DataType.Password)]
        public string TestApiKey { get; set; }

        [NopResourceDisplayName("Plugins.Shipping.EasyPost.Configuration.Fields.UseSandbox")]
        public bool UseSandbox { get; set; }

        [NopResourceDisplayName("Plugins.Shipping.EasyPost.Configuration.Fields.UseAllAvailableCarriers")]
        public bool UseAllAvailableCarriers { get; set; }

        [NopResourceDisplayName("Plugins.Shipping.EasyPost.Configuration.Fields.CarrierAccounts")]
        public IList<SelectListItem> AvailableCarrierAccounts { get; set; }
        public IList<string> CarrierAccounts { get; set; }

        [NopResourceDisplayName("Plugins.Shipping.EasyPost.Configuration.Fields.AddressVerification")]
        public bool AddressVerification { get; set; }

        [NopResourceDisplayName("Plugins.Shipping.EasyPost.Configuration.Fields.StrictAddressVerification")]
        public bool StrictAddressVerification { get; set; }

        #endregion
    }
}

Plugins/Nop.Plugin.Shipping.EasyPost/Controllers/EasyPostController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Runtime.Serialization;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Nop.Core;
using Nop.Core.Domain.Common;
using Nop.Core.Domain.Shipping;
using Nop.Core.Http;
using Nop.Core.Infrastructure;
using Nop.Plugin.Shipping.EasyPost.Domain.Batch;
using Nop.Plugin.Shipping.EasyPost.Domain.Shipment;
using Nop.Plugin.Shipping.EasyPost.Factories;
using Nop.Plugin.Shipping.EasyPost.Models.Batch;
using Nop.Plugin.Shipping.EasyPost.Models.Configuration;
using Nop.Plugin.Shipping.EasyPost.Models.Pickup;
using Nop.Plugin.Shipping.EasyPost.Models.Shipment;
using Nop.Plugin.Shipping.EasyPost.Services;
using Nop.Services;
using Nop.Services.Configuration;
using Nop.Services.Directory;
using Nop.Services.Helpers;
using Nop.Services.Localization;
using Nop.Services.Messages;
using Nop.Services.Security;
using Nop.Services.Shipping;
using Nop.Web.Areas.Admin.Factories;
using Nop.Web.Areas.Admin.Infrastructure.Mapper.Extensions;
using Nop.Web.Areas.Admin.Models.Orders;
using Nop.Web.Framework;
using Nop.Web.Framework.Controllers;
using Nop.Web.Framework.Models.Extensions;
using Nop.Web.Framework.Mvc.Filters;

namespace Nop.Plugin.Shipping.EasyPost.Controllers
{
    [AuthorizeAdmin]
    [Area(AreaNames.Admin)]
    [AutoValidateAntiforgeryToken]
    public class EasyPostController : BasePluginController
    {
        #region Fields

        private readonly EasyPostModelFactory _easyPostModelFactory;
        private readonly EasyPostService _easyPostService;
        private readonly EasyPostSettings _easyPostSettings;
        private readonly ICurrencyService _currencyService;
        private readonly IDateTimeHelper _dateTimeHelper;
        private readonly IHttpClientFactory _httpClientFactory;
        private readonly ILocalizationService _localizationService;
        private readonly IMeasureService _measureService;
        private readonly INopFileProvider _nopFileProvider;
        private readonly INotificationService _notificationService;
        private readonly IOrderModelFactory _orderModelFactory;
        private readonly IPermissionService _permissionService;
        private readonly ISettingService _settingService;
        private readonly IShipmentService _shipmentService;
        private readonly ShippingSettings _shippingSettings;

        #endregion

        #region Ctor

        public EasyPostController(EasyPostModelFactory easyPostModelFactory,
            EasyPostService easyPostService,
            EasyPostSettings easyPostSettings,
            ICurrencyService currencyService,
            IDateTimeHelper dateTimeHelper,
            IHttpClientFactory httpClientFactory,
            ILocalizationService localizationService,
            IMeasureService measureService,
            INopFileProvider nopFileProvider,
            INotificationService notificationService,
            IOrderModelFactory orderModelFactory,
            IPermissionService permissionService,
            ISettingService settingService,
            IShipmentService shipmentService,
            ShippingSettings shippingSettings)
        {
            _easyPostModelFactory = easyPostModelFactory;
            _easyPostService = easyPostService;
            _easyPostSettings = easyPostSettings;
            _currencyService = currencyService;
            _dateTimeHelper = dateTimeHelper;
            _httpClientFactory = httpClientFactory;
            _localizationService = localizationService;
            _measureService = measureService;
            _nopFileProvider = nopFileProvider;
            _notificationService = notificationService;
            _orderModelFactory = orderModelFactory;
            _permissionService = permissionService;
            _settingService = settingService;
            _shipmentService = shipmentService;
            _shippingSettings = shippingSettings;
        }

        #endregion

        #region Methods

        #region Configuration

        public async Task<IActionResult> Configure()
        {
            if (!await _permissionService.AuthorizeAsync(StandardPermissionProvider.ManageShippingSettings))
                return AccessDeniedView();

            var model = new ConfigurationModel
            {
                ApiKey = _easyPostSettings.ApiKey,
                TestApiKey = _easyPostSettings.TestApiKey,
                UseSandbox = _easyPostSettings.UseSandbox,
                UseAllAvailableCarriers = _easyPostSettings.UseAllAvailableCarriers,
                CarrierAccounts = _easyPostSettings.CarrierAccounts ?? new(),
                AddressVerification = _easyPostSettings.AddressVerification,
                StrictAddressVerification = _easyPostSettings.StrictAddressVerification
            };

            //get configured carrier accounts
            if (!_easyPostSettings.UseSandbox)
            {
                var (accounts, accountsError) = await _easyPostService.GetCarrierAccountsAsync();
                if (!string.IsNullOrEmpty(accountsError))
                {
                    //accounts are available only in production, so don't display errors in sandbox mode
                    var locale = await _localizationService.GetResourceAsync("Plugins.Shipping.EasyPost.Error");
                    var errorMessage = string.Format(locale, accountsError, Url.Action("List", "Log"));
                    _notificationService.ErrorNotification(errorMessage, false);
                }

                model.AvailableCarrierAccounts = accounts?.Select(account => new SelectListItem
                {
                    Value = account.id,
                    Text = account.readable ?? account.type,
                    Selected = _easyPostSettings.CarrierAccounts?.Contains(account.id) ?? false
                }).ToList() ?? new();
            }

            //check default currency availability
            var currency = await _currencyService.GetCurrencyByCodeAsync(EasyPostDefaults.CurrencyCode);
            if (currency is null)
            {
                var locale = await _localizationService.GetResourceAsync("Plugins.Shipping.EasyPost.Configuration.Currency.Warning");
                var warningMessage = string.Format(locale, EasyPostDefaults.CurrencyCode, Url.Action("List", "Currency"));
                _notificationService.WarningNotification(warningMessage, false);
            }

            //check default dimension and weight measures availability
            var weight = await _measureService.GetMeasureWeightBySystemKeywordAsync(EasyPostDefaults.MeasureWeightSystemName);
            var dimension = await _measureService.GetMeasureDimensionBySystemKeywordAsync(EasyPostDefaults.MeasureDimensionSystemName);
            if (weight is null || dimension is null)
            {
                var locale = await _localizationService.GetResourceAsync("Plugins.Shipping.EasyPost.Configuration.Measures.Warning");
                var warningMessage = string.Format(locale,
                    EasyPostDefaults.MeasureDimensionSystemName, EasyPostDefaults.MeasureWeightSystemName, Url.Action("List", "Measure"));
                _notificationService.WarningNotification(warningMessage, false);
            }

            return View("~/Plugins/Shipping.EasyPost/Views/Configuration/Configure.cshtml", model);
        }

        [HttpPost]
        public async Task<IActionResult> Configure(ConfigurationModel model)
        {
            if (!await _permissionService.AuthorizeAsync(StandardPermissionProvider.ManageShippingSettings))
                return AccessDeniedView();

            if (!ModelState.IsValid)
                return await Configure();

            _easyPostSettings.ApiKey = model.ApiKey;
            _easyPostSettings.TestApiKey = model.TestApiKey;
            _easyPostSettings.UseSandbox = model.UseSandbox;
            _easyPostSettings.UseAllAvailableCarriers = model.UseAllAvailableCarriers;
            _easyPostSettings.CarrierAccounts = model.CarrierAccounts?.ToList();
            _easyPostSettings.AddressVerification = model.AddressVerification;
            _easyPostSettings.StrictAddressVerification = model.StrictAddressVerification;
            await _settingService.SaveSettingAsync(_easyPostSettings);

            //reset client configuration
            EasyPostService.ResetClientConfiguration();

            //create webhook
            var (webhook, webhookError) = await _easyPostService.CreateWebhookAsync();
            if (!string.IsNullOrEmpty(webhookError))
            {
                var locale = await _localizationService.GetResourceAsync("Plugins.Shipping.EasyPost.Error");
                var errorMessage = string.Format(locale, webhookError, Url.Action("List", "Log"));
                _notificationService.ErrorNotification(errorMessage, false);
            }
            await _settingService.SetSettingAsync($"{nameof(EasyPostSettings)}.{nameof(EasyPostSettings.WebhookUrl)}", webhook?.url);

            _notificationService.SuccessNotification(await _localizationService.GetResourceAsync("Admin.Plugins.Saved"));

            return await Configure();
        }

        #endregion

        #region Shipment

        [HttpPost]
        public async Task<IActionResult> UpdateShipment(ShipmentDetailsModel model)
        {
            if (!await _permissionService.AuthorizeAsync(StandardPermissionProvider.ManageOrders))
                return AccessDeniedView();

            var shipment = await _shipmentService.GetShipmentByIdAsync(model.Id);
            if (shipment is not null)
            {
                string getAttributeValue(Enum enumValue) => enumValue.GetType().GetMember(enumValue.ToString()).FirstOrDefault()
                    ?.GetCustomAttributes(false).OfType<EnumMemberAttribute>().FirstOrDefault()
                    ?.Value is string value && value != "---" ? value : null;

Plugins/Nop.Plugin.Shipping.EasyPost/Views/Configuration/Configure.cshtml
@model ConfigurationModel

@{
    Layout = "_ConfigurePlugin";
}

<script>
    $(document).ready(function () {
        $("#@Html.IdFor(model => model.UseSandbox)").click(toggleSandbox);
        $("#@Html.IdFor(model => model.UseAllAvailableCarriers)").click(toggleAllCarriers);
        $("#@Html.IdFor(model => model.AddressVerification)").click(toggleAddressVerification);
        toggleSandbox();
        toggleAddressVerification();
    });

    function toggleSandbox() {
        if ($('#@Html.IdFor(model => model.UseSandbox)').is(':checked')) {
            $('#api-key').hideElement();
            $('#test-api-key').showElement();
            $('#carriers').hideElement();
        } else {
            $('#api-key').showElement();
            $('#test-api-key').hideElement();
            $('#carriers').showElement();
            toggleAllCarriers();
        }
    }

    function toggleAllCarriers() {
        if ($('#@Html.IdFor(model => model.UseAllAvailableCarriers)').is(':checked')) {
            $('#carrier-accounts').hideElement();
        } else {
            $('#carrier-accounts').showElement();
        }
    }

    function toggleAddressVerification() {
        if ($('#@Html.IdFor(model => model.AddressVerification)').is(':checked')) {
            $('#strict-address-verification').showElement();
        } else {
            $('#strict-address-verification').hideElement();
        }
    }
</script>

<form asp-controller="EasyPost" asp-action="Configure" method="post">
    <div class="cards-group">

        <div class="card card-default no-margin">
            <div class="card-header">
                @T("Plugins.Shipping.EasyPost.Configuration.Credentials")
            </div>
            <div class="card-body">
                <p>
                    To enable this shipping provider, you'll need to:<br />
                    <br />
                    1. <a href="https://www.easypost.com/signup" target="_blank">Sign up for an EasyPost account</a><br />
                    2. Enter your carrier specific credentials on the <a href="https://www.easypost.com/account/carriers" target="_blank">Carrier Account Dashboard</a><br />
                    <em>Note: Unless you've entered your carrier information for other carriers, you'll just receive USPS rates.</em><br />
                    <em>Note: Negotiated rates are only available in Production mode.</em><br />
                    3. Find your <a href="https://www.easypost.com/account/api-keys" target="_blank">API keys</a>. Use Test key for testing purposes and switch to your Production key when you're ready to buy real postage.<br />
                    See <a href="https://docs.nopcommerce.com/en/getting-started/configure-shipping/shipping-providers/easypost.html" target="_blank">documentation</a> for more information.<br />
                </p>
                <div class="form-group row">
                    <div class="col-md-3">
                        <nop-label asp-for="UseSandbox" />
                    </div>
                    <div class="col-md-9">
                        <nop-editor asp-for="UseSandbox" />
                        <span asp-validation-for="UseSandbox"></span>
                    </div>
                </div>
                <div class="form-group row" id="api-key">
                    <div class="col-md-3">
                        <nop-label asp-for="ApiKey" />
                    </div>
                    <div class="col-md-9">
                        <nop-editor asp-for="ApiKey" asp-required="true" html-attributes="@(new { value = Model.ApiKey })" />
                        <span asp-validation-for="ApiKey"></span>
                    </div>
                </div>
                <div class="form-group row" id="test-api-key">
                    <div class="col-md-3">
                        <nop-label asp-for="TestApiKey" />
                    </div>
                    <div class="col-md-9">
                        <nop-editor asp-for="TestApiKey" html-attributes="@(new { value = Model.TestApiKey })" />
                        <span asp-validation-for="TestApiKey"></span>
                    </div>
                </div>
            </div>
        </div>

        @if (!string.IsNullOrEmpty(Model.ApiKey))
        {
            <div class="card card-default no-margin" id="carriers">
                <div class="card-header">
                    @T("Plugins.Shipping.EasyPost.Configuration.Carriers")
                </div>
                <div class="card-body">
                    <p>
                        When shipment is creating, the service responds with shipping rates for the all carriers you've enabled.
                        If you wish to restrict your rating to a specific carrier, specify carrier accounts here.
                    </p>
                    <div class="form-group row">
                        <div class="col-md-3">
                            <nop-label asp-for="UseAllAvailableCarriers" />
                        </div>
                        <div class="col-md-9">
                            <nop-editor asp-for="UseAllAvailableCarriers" />
                            <span asp-validation-for="UseAllAvailableCarriers"></span>
                        </div>
                    </div>
                    <div class="form-group row" id="carrier-accounts">
                        <div class="col-md-3">
                            <nop-label asp-for="AvailableCarrierAccounts" />
                        </div>
                        <div class="col-md-9">
                            @if (!Model.AvailableCarrierAccounts.Any())
                            {
                                @T("Plugins.Shipping.EasyPost.Configuration.Fields.CarrierAccounts.None")
                            }
                            @foreach (var account in Model.AvailableCarrierAccounts)
                            {
                                <div class="form-check">
                                    <label class="form-check-label">
                                        <input class="form-check-input" type="checkbox" name="@(nameof(Model.CarrierAccounts))" value="@(account.Value)" checked="@(account.Selected)" />
                                        @(account.Text)
                                    </label>
                                </div>
                            }
                        </div>
                    </div>
                </div>
            </div>
        }

        <div class="card card-default no-margin">
            <div class="card-header">
                @T("Plugins.Shipping.EasyPost.Configuration.AddressVerification")
            </div>
            <div class="card-body">
                <p>
                    EasyPost offers several verification tools that can be used to detect deliverability issues, correct minor errors in spelling/formatting, and determine if an address is residential or not (which has a significant effect on ahipment rating for many carriers).<br />
                    The address verification service supports 240+ countries. See the <a href="https://www.easypost.com/docs/address-verification-by-country" target="_blank">full listing</a> to see which verification level is available for each country. <br />
                    International AVS is also a premium, stand-alone service that must be subscribed to in order to be used. If you'd like to learn more about International AVS, <a href="https://www.easypost.com/talk-to-easypost" target="_blank">contact representatives</a> for more information.
                </p>
                <div class="form-group row">
                    <div class="col-md-3">
                        <nop-label asp-for="AddressVerification" />
                    </div>
                    <div class="col-md-9">
                        <nop-editor asp-for="AddressVerification" />
                        <span asp-validation-for="AddressVerification"></span>
                    </div>
                </div>
                <nop-nested-setting asp-for="AddressVerification" id="strict-address-verification" disable-auto-generation="true">
                    <div class="form-group row">
                        <div class="col-md-3">
                            <nop-label asp-for="StrictAddressVerification" />
                        </div>
                        <div class="col-md-9">
                            <nop-editor asp-for="StrictAddressVerification" />
                            <span asp-validation-for="StrictAddressVerification"></span>
                        </div>
                    </div>
                </nop-nested-setting>
            </div>
        </div>

        <div class="form-group row">
            <div class="col-md-9 offset-md-3">
                <button type="submit" name="save" class="btn btn-primary">@T("Admin.Common.Save")</button>
            </div>
        </div>

    </div>
</form>